
CREATE TABLE GENDERS(
ID NUMBER NOT NULL,
NAME VARCHAR2(255)
);

ALTER TABLE GENDERS add CONSTRAINT GENDERS_pk PRIMARY KEY (ID);


CREATE SEQUENCE GENDERS_id_seq  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE OR REPLACE TRIGGER GENDERS_id_trigger
BEFORE INSERT ON GENDERS 
FOR EACH ROW

BEGIN
  SELECT GENDERS_id_seq.NEXTVAL
  INTO   :new.id 
  FROM   dual;
END;




CREATE TABLE JOBS(
ID NUMBER NOT NULL,
NAME VARCHAR2(255),
SALARY NUMBER(9,2)
);  



ALTER TABLE JOBS add CONSTRAINT JOBS_pk PRIMARY KEY (ID);


CREATE SEQUENCE JOBS_id_seq  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



CREATE OR REPLACE TRIGGER JOBS_id_trigger
BEFORE INSERT ON JOBS 
FOR EACH ROW

BEGIN
  SELECT JOBS_id_seq.NEXTVAL
  INTO   :new.id 
  FROM   dual;
END;



CREATE TABLE EMPLOYEES(
ID NUMBER,
GENDER_ID NUMBER ,
JOB_ID NUMBER,
NAME VARCHAR2(255),
LAST_NAME VARCHAR2(255),
BIRTHDATE DATE
);


ALTER TABLE EMPLOYEES add CONSTRAINT EMPLOYEES_pk PRIMARY KEY (ID);

CREATE SEQUENCE EMPLOYEES_id_seq  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER EMPLOYEES_id_trigger
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW

BEGIN
  SELECT EMPLOYEES_id_seq.NEXTVAL
  INTO   :new.id 
  FROM   dual;
END;


ALTER TABLE EMPLOYEES
add 
    CONSTRAINT fk_GENDER_id
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDERS(ID);




ALTER TABLE EMPLOYEES
add 
    CONSTRAINT fk_JOBS_id
    FOREIGN KEY (JOB_ID)
    REFERENCES JOBS(ID);
    
    
    
    
    

CREATE TABLE EMPLOYEES_WORKED_HOURS(

    ID NUMBER,
    EMPLOYEE_ID NUMBER,
    WORKED_HOURS NUMBER,
    WORKED_DATE  DATE 

    );




ALTER TABLE EMPLOYEES_WORKED_HOURS add CONSTRAINT JEMPLOYEES_WORKED_HOURS_pk PRIMARY KEY (ID);

CREATE SEQUENCE EMPLOYEES_WORKED_HOURS_id_seq  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE OR REPLACE TRIGGER EMPLOYEES_WORKED_HOURS_id_trigger
BEFORE INSERT ON EMPLOYEES_WORKED_HOURS 
FOR EACH ROW

BEGIN
  SELECT EMPLOYEES_WORKED_HOURS_id_seq.NEXTVAL
  INTO   :new.id 
  FROM   dual;
END;



SELECT * FROM GENDERS;

SELECT * FROM JOBS;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES_WORKED_HOURS;

